permalink:           pretty

# Setup
title:               'Logaty Library Documentation'
tagline:             'Logaty Library Documentation'
baseurl:             ''
#'https://anzawi.github.io/logaty'

sass:
  style: compressed

# About/contact
author:
  name:              Mohammad Anzawi
  url:               https://github.com/anzawi
  email:             m.anzawi2013@gmial.com


# Custom vars
version:             1.0.0

exclude:             [vendor]

github:
  repository_url:    https://github.com/anzawi/logaty

twitter:
  handle:            bakeryhq


defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      author: "Mohammad Anzawi"